export const MAX_LAYOUT_WIDTH = "1560";
export const topics: string[] = ["getOut", "startLesson", "endLesson", "streamingEducationsUpdate"];

const universiteler = [
    "Adana Alparslan Türkeş Bilim ve Teknoloji Üniversitesi",
    "Adıyaman Üniversitesi",
    "Afyonkarahisar Sağlık Bilimleri Üniversitesi",
    "Afyonkarahisar Tarım Bilimleri ve Teknoloji Üniversitesi",
    "Ağrı İbrahim Çeçen Üniversitesi",
    "Aksaray Üniversitesi",
    "Amasya Üniversitesi",
    "Anadolu Üniversitesi",
    "Ankara Sosyal Bilimler Üniversitesi",
    "Ankara Üniversitesi",
    "Ardahan Üniversitesi",
    "Artvin Çoruh Üniversitesi",
    "Atatürk Üniversitesi",
    "Balıkesir Üniversitesi",
    "Bandırma Onyedi Eylül Üniversitesi",
    "Bartın Üniversitesi",
    "Batman Üniversitesi",
    "Bayburt Üniversitesi",
    "Beykent Üniversitesi",
    "Bilecik Şeyh Edebali Üniversitesi",
    "Bingöl Üniversitesi",
    "Bursa Teknik Üniversitesi",
    "Bursa Uludağ Üniversitesi",
    "Çanakkale Onsekiz Mart Üniversitesi",
    "Çankaya Üniversitesi",
    "Çankırı Karatekin Üniversitesi",
    "Çukurova Üniversitesi",
    "Deniz Harp Okulu",
    "Denizcilik Fakültesi",
    "Dicle Üniversitesi",
    "Dokuz Eylül Üniversitesi",
    "Dumlupınar Üniversitesi",
    "Düzce Üniversitesi",
    "Ege Üniversitesi",
    "Erciyes Üniversitesi",
    "Erzincan Binali Yıldırım Üniversitesi",
    "Erzurum Teknik Üniversitesi",
    "Eskişehir Osmangazi Üniversitesi",
    "Fatih Sultan Mehmet Vakıf Üniversitesi",
    "Fırat Üniversitesi",
    "Galatasaray Üniversitesi",
    "Gazi Üniversitesi",
    "Gaziantep İslam Bilim ve Teknoloji Üniversitesi",
    "Gaziantep Üniversitesi",
    "Gebze Teknik Üniversitesi",
    "Giresun Üniversitesi",
    "Gümüşhane Üniversitesi",
    "Hacettepe Üniversitesi",
    "Hakkari Üniversitesi",
    "Harran Üniversitesi",
    "Hitit Üniversitesi",
    "Iğdır Üniversitesi",
    "İnönü Üniversitesi",
    "İskenderun Teknik Üniversitesi",
    "İstanbul Medeniyet Üniversitesi",
    "İstanbul Rumeli Üniversitesi",
    "İstanbul Teknik Üniversitesi",
    "İstanbul Üniversitesi",
    "İstanbul Sabahattin Zaim Üniversitesi",
    "İstanbul Yeni Yüzyıl Üniversitesi",
    "İstinye Üniversitesi",
    "İzmir Bakırçay Üniversitesi",
    "İzmir Demokrasi Üniversitesi",
    "İzmir Ekonomi Üniversitesi",
    "İzmir Kâtip Çelebi Üniversitesi",
    "İzmir Yüksek Teknoloji Enstitüsü",
    "Kafkas Üniversitesi",
    "Kahramanmaraş Sütçü İmam Üniversitesi",
    "Karabük Üniversitesi",
    "Karadeniz Teknik Üniversitesi",
    "Karamanoğlu Mehmetbey Üniversitesi",
    "Kastamonu Üniversitesi",
    "Kırıkkale Üniversitesi",
    "Kırklareli Üniversitesi",
    "Kilis 7 Aralık Üniversitesi",
    "Kocaeli Üniversitesi",
    "Konya Teknik Üniversitesi",
    "Kütahya Dumlupınar Üniversitesi",
    "Malatya Turgut Özal Üniversitesi",
    "Manisa Celal Bayar Üniversitesi",
    "Mardin Artuklu Üniversitesi",
    "Marmara Üniversitesi",
    "Mehmet Akif Ersoy Üniversitesi",
    "Mersin Üniversitesi",
    "Mimar Sinan Güzel Sanatlar Üniversitesi",
    "Muğla Sıtkı Koçman Üniversitesi",
    "Muş Alparslan Üniversitesi",
    "Mustafa Kemal Üniversitesi",
    "Necmettin Erbakan Üniversitesi",
    "Nevşehir Hacı Bektaş Veli Üniversitesi",
    "Niğde Ömer Halisdemir Üniversitesi",
    "Nişantaşı Üniversitesi",
    "Ondokuz Mayıs Üniversitesi",
    "Ordu Üniversitesi",
    "Orta Doğu Teknik Üniversitesi",
    "Osmaniye Korkut Ata Üniversitesi",
    "Pamukkale Üniversitesi",
    "Polis Akademisi",
    "Recep Tayyip Erdoğan Üniversitesi",
    "Sakarya Uygulamalı Bilimler Üniversitesi",
    "Sakarya Üniversitesi",
    "Selçuk Üniversitesi",
    "Siirt Üniversitesi",
    "Sinop Üniversitesi",
    "Sivas Bilim ve Teknoloji Üniversitesi",
    "Süleyman Demirel Üniversitesi",
    "Şırnak Üniversitesi",
    "Trabzon Üniversitesi",
    "Türk-Alman Üniversitesi",
    "Türkiye Uluslararası İslam, Bilim ve Teknoloji Üniversitesi",
    "Ufuk Üniversitesi",
    "Uluslararası Antalya Üniversitesi",
    "Uşak Üniversitesi",
    "Yalova Üniversitesi",
    "Yıldırım Beyazıt Üniversitesi",
    "Yıldız Teknik Üniversitesi",
    "Yüzüncü Yıl Üniversitesi",
    "Zonguldak Bülent Ecevit Üniversitesi"
]
